### ISSUE TITLE
[1.16.5] CTD on placing a cooking pot

### ISSUE THREAD

**Issue by MisakiCopperrose** [ikutv/farmersdelightintegration#4]
Description
The games crashes when placing a cooking pot no matter where or on what.

Steps to reproduce:
I got myself a cooking pot and placed it.

Expected behavior:
There should've been placed a pot, without the games crashing.

Logs
Crashlog: https://pastebin.com/KYuGcK54
Latest log https://pastebin.com/upwPK0UJ

Mod list:
See crashlog under Logs

After testing by deleting some mods, it turned out yours to be causing it. Hope these logs will help crushing some bugs!

[crash-2021-02-28_23.00.29-client.txt](https://github.com/ikutv/farmersdelightintegration/files/6058151/crash-2021-02-28_23.00.29-client.txt)
[crash-2021-02-28_22.53.41-client.txt](https://github.com/ikutv/farmersdelightintegration/files/6058152/crash-2021-02-28_22.53.41-client.txt)
[crash-2021-02-26_23.59.25-client.txt](https://github.com/ikutv/farmersdelightintegration/files/6058153/crash-2021-02-26_23.59.25-client.txt)

**Comment by ikutv** [comment]
This is fixed in the latest version updated today,
